apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-pod
  labels:
    name: voting-pod
    app: voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-pod
      app: voting-app
  template:
    metadata: 
      name: voting-pod
      labels:
        name: voting-pod
        app: voting-app
    spec:
      containers:
        - name: voting-app
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-pod
    app: voting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: voting-pod
    app: voting-app