apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: result-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30006
  selector:
    name: result-pod
    app: result-app