apiVersion: v1
kind: Service
metadata:
  name: myapp-deployment-service
spec:
  type: NodePort
  selector:
    tier: frontend
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009
