apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      server: nginx
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        server: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
